FROM node:12

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm run build
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

#COPY ./docker-entrypoint.sh /usr/local/bin
#ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

EXPOSE 8080
CMD [ "npm", "start" ]
