name: OpenShift
env:
  REGISTRY: https://hub.docker.com/r/iraklico/app-builder
  REGISTRY_USER: ${{secrets.DOCKER_USER}}
  REGISTRY_PASSWORD: ${{secrets.DOCKER_PASSWORD}}  
  # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "irakli-builder"
  APP_NAME: "app-builder"
  TAG: ""  
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - id: 'release_manager'
        uses: ichalagashvili/release-manager@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          owner: 'ichalagashvili'
          repo: 'app-builder'
      - uses: actions/checkout@v2
      - name: Build from Dockerfile
        uses: redhat-actions/buildah-build@v1
        with:
          image: ${{ env.APP_NAME }}
          tag: ${{ env.TAG }}
          # If you don't have a dockerfile, see:
          # https://github.com/redhat-actions/buildah-build#building-from-scratch
          # Otherwise, point this to your Dockerfile relative to the repository root.
          dockerfiles: |
            ./Dockerfile
      # https://github.com/redhat-actions/push-to-registry#readme
      - name: Push to registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v1
        with:
          image: ${{ env.APP_NAME }}
          tag: iraklico/app-builder:${{ steps.release_manager.outputs.nextTagName }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      - uses: azure/setup-helm@v1
        with:
          version: '2.16.7'
        id: install  
      - name: Create and expose app
        run: |
          echo "Initiating protocol"
          echo ${{ steps.release_manager.outputs.nextTagName }}
          VERSION=${{ steps.release_manager.outputs.nextTagName }}
          # 1. Clone helm quickstart from https://github.com/entando-k8s/entando-helm-quickstart/
          # git clone https://github.com/entando-k8s/entando-helm-quickstart/
          # git clone https://github.com/ichalagashvili/entando-helm-quickstart
          # 1.1 CD into helm repo
          # cd entando-helm-quickstart
          # 2. Run its necessary steps. Probably overwrite values.yaml file with our config
          # sed -i 's/your.domain.suffix.com/apps.rd.entando.org/g' values.yaml
          # cat values.yaml
          # echo "values shown"
          helm version
          # echo "helm is good"
          # 3. generate new yaml and create new app
          # helm template --name=irakli-app-builder  --namespace=irakli-builder ./ > irakli-builder.yaml
          # echo $GITHUB_WORKSPACE
          # @TODO change app-builder version
          # cat $GITHUB_WORKSPACE/configmap.yaml
          # 3.1 Do I need to run below line?
          # kubectl create -f irakli-builder.yaml
          # 4. change project via
          oc project irakli-builder
          echo "project changed!"
          # 5. Delete old app
          #oc delete -f irakli-builder.yaml
          #oc delete -f $GITHUB_WORKSPACE/configmap.yaml
          kubectl delete "$(kubectl api-resources --namespaced=true --verbs=delete -o name | tr "\n" "," | sed -e 's/,$//')" --all
          echo "Deletion successfully executed."
          # Add new version for app-builder
          sed -i 's/.*APP_BUILDER_URL.*/    {"version":'\""$VERSION"\"',"executable-type":"jvm","registry":"docker.io","organization":"iraklico"}/' $GITHUB_WORKSPACE/configmap.yaml
          cat $GITHUB_WORKSPACE/configmap.yaml
          # 6. Deploy new app
          oc create -f $GITHUB_WORKSPACE/configmap.yaml
          echo "New app has been deployed!"

      - name: View application route
        run: |
          echo "======================== Your application is available at: ========================"
          echo http://quickstart-irakli-builder.apps.rd.entando.org/app-builder/
          echo "==================================================================================="
          echo
          echo "You might need to wait 5-10 minutes until the deployment process is completely finished"
