name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: 'release_manager'
      - uses: ichalagashvili/release-manager@master
        with:
          who-to-greet: 'Mona the Octocat 1'
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: |
          echo ${{ steps.release_manager.outputs.nextTagName }}
          VERSION=${{ steps.release_manager.outputs.nextTagName }}
          echo VERSION=$VERSION
          docker build . --file Dockerfile --tag ichalagashvili/iraklis-builder:$VERSION
          docker tag ichalagashvili/iraklis-builder:$VERSION ichalagashvili/iraklis-builder:$VERSION
      # - name: Docker Push
      #   run: docker push ichalagashvili/iraklis-builder
