name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of app-builder
        uses: rez0n/actions-github-release@main
        id: appbuilder_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "ichalagashvili/app-builder"
          type: "stable"
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: |
          CURRENT_VERSION=${{ steps.appbuilder_release.outputs.release }}
          echo CURRENT_VERSION=$CURRENT_VERSION
          VERSION=$(echo $CURRENT_VERSION | awk 'BEGIN{FS=OFS="."} {$3+=1} 1')
          echo VERSION=$VERSION
          docker build . --file Dockerfile --tag ichalagashvili/iraklis-builder:$VERSION
          docker tag ichalagashvili/iraklis-builder:$VERSION ichalagashvili/iraklis-builder:$VERSION
      - name: Docker Push
        run: docker push ichalagashvili/iraklis-builder
