name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |

        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: get-npm-version
    - id: package-version
    - uses: martinbeentjes/npm-get-version-action@master
    - name: Build the Docker image
      run: |

        # Strip git ref prefix from version
        VERSION=${{ steps.package-version.outputs.current-version}}
        echo VERSION
        VERSION = $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g'
        echo VERSION
        
        echo VERSION=$VERSION
        docker build . --file Dockerfile --tag ichalagashvili/iraklis-builder:$VERSION
        docker tag ichalagashvili/iraklis-builder:$VERSION ichalagashvili/iraklis-builder:$VERSION
    - name: Docker Push
      run: docker push ichalagashvili/iraklis-builder