on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: My release manager job 5
    steps:
    - name: Hello world action step
      id: hello
      uses: ichalagashvili/release-manager@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        owner: 'ichalagashvili'
        repo: 'app-builder'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
