name: Test lint, sass, coverage, working on multiple node versions

on:
  pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and lint source code
      run: |
        npm install
        npm run lint
      env:
        CI: true
    - name: lint sass code
      run: |
        npm run sass-lint
      env:
        CI: true
    - name: test code and check coverage
      run: |
        npm run coverage
      env:
        CI: true

